version: '3.1'

volumes:
  pg_rest:

services:
  rest_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=test
    volumes:
      - pg_rest:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rest_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://rest_db:5432/test'
      JAVA_OPTS: '-Xmx512m'