-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.coin
(
    id bigserial NOT NULL,
    portfolio_coin_id bigint NOT NULL DEFAULT nextval('coin_portfolio_id_seq'::regclass),
    coin_name text COLLATE pg_catalog."default" NOT NULL,
    coin_code text COLLATE pg_catalog."default" NOT NULL,
    volume double precision NOT NULL,
    usd_price double precision NOT NULL,
    last_price double precision[] NOT NULL,
    CONSTRAINT coin_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coins
(
    id bigserial NOT NULL,
    coin_name text COLLATE pg_catalog."default" NOT NULL,
    coin_code text COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    h1 double precision NOT NULL,
    h24 double precision NOT NULL,
    d7 double precision NOT NULL,
    market_cap double precision NOT NULL,
    volume double precision NOT NULL,
    last_price double precision[] NOT NULL,
    CONSTRAINT coins_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.deal
(
    id bigserial NOT NULL,
    portfolio_id bigserial NOT NULL,
    date text COLLATE pg_catalog."default" NOT NULL,
    type text COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    volume double precision NOT NULL,
    coin_name text COLLATE pg_catalog."default" NOT NULL,
    coin_code text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT deal_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.exchanges
(
    id bigserial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    score double precision NOT NULL,
    volume24h double precision NOT NULL,
    markets double precision NOT NULL,
    coins double precision NOT NULL,
    last_volume double precision[] NOT NULL,
    CONSTRAINT exchanges_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.portfolio
(
    id bigserial NOT NULL,
    profile_volume_usd double precision[] NOT NULL,
    profile_volume_btc double precision[] NOT NULL,
    current_volume_usd double precision NOT NULL,
    current_volume_btc double precision NOT NULL,
    CONSTRAINT portfolio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.trend
(
    id bigserial NOT NULL,
    coin_name text COLLATE pg_catalog."default" NOT NULL,
    coin_code text COLLATE pg_catalog."default" NOT NULL,
    h24 double precision NOT NULL,
    CONSTRAINT trend_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.coin
    ADD FOREIGN KEY (portfolio_coin_id)
    REFERENCES public.portfolio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.deal
    ADD FOREIGN KEY (portfolio_id)
    REFERENCES public.portfolio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;