-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.coin
(
    id bigserial NOT NULL,
    portfolio_id bigserial,
    coin_name text COLLATE pg_catalog."default",
    coin_code text COLLATE pg_catalog."default",
    volume double precision,
    usd_price double precision,
    last_price double precision[],
    CONSTRAINT coin_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coins
(
    id bigserial NOT NULL,
    coin_name text COLLATE pg_catalog."default",
    coin_code text COLLATE pg_catalog."default",
    price double precision,
    h1 double precision,
    h24 double precision,
    d7 double precision,
    market_cap double precision,
    volume double precision,
    last_price double precision[],
    CONSTRAINT coins_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.deal
(
    id bigserial NOT NULL,
    portfolio_id bigserial,
    date text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    price double precision,
    volume double precision,
    coin_name text COLLATE pg_catalog."default",
    coin_code text COLLATE pg_catalog."default",
    CONSTRAINT deal_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.exchanges
(
    id bigserial NOT NULL,
    name text COLLATE pg_catalog."default",
    score double precision,
    volume24h double precision,
    markets double precision,
    coins double precision,
    last_volume double precision[],
    CONSTRAINT exchanges_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.portfolio
(
    id bigserial NOT NULL,
    profile_volume_usd double precision[],
    profile_volume_btc double precision[],
    current_volume_usd double precision,
    current_volume_btc double precision,
    CONSTRAINT portfolio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.trend
(
    id bigserial NOT NULL,
    coin_name text COLLATE pg_catalog."default",
    coin_code text COLLATE pg_catalog."default",
    h24 double precision,
    CONSTRAINT trend_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.coin
    ADD FOREIGN KEY (portfolio_id)
    REFERENCES public.portfolio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.deal
    ADD FOREIGN KEY (portfolio_id)
    REFERENCES public.portfolio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;