-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Coins"
(
    coin_name text NOT NULL,
    coin_code text NOT NULL,
    price double precision NOT NULL,
    h1 double precision NOT NULL,
    h24 double precision NOT NULL,
    d7 double precision NOT NULL,
    market_cup double precision NOT NULL,
    volume double precision NOT NULL,
    last_price double precision[] NOT NULL,
    CONSTRAINT "Coins_pkey" PRIMARY KEY (coin_code)
);

CREATE TABLE IF NOT EXISTS public."Deal"
(
    login text NOT NULL,
    date text NOT NULL,
    type text NOT NULL,
    price double precision NOT NULL,
    volume double precision NOT NULL,
    coin_name text NOT NULL,
    coin_code text NOT NULL,
    CONSTRAINT "Deal_pkey" PRIMARY KEY (login)
);

CREATE TABLE IF NOT EXISTS public."Coin"
(
    login text NOT NULL,
    coin_name text NOT NULL,
    coin_code text NOT NULL,
    volume double precision NOT NULL,
    usd_price double precision NOT NULL,
    last_price double precision[] NOT NULL,
    CONSTRAINT "Coin_pkey" PRIMARY KEY (login)
);

CREATE TABLE IF NOT EXISTS public."Trend"
(
    coin_name text NOT NULL,
    coin_code text NOT NULL,
    h24 double precision NOT NULL,
    CONSTRAINT "Trend_pkey" PRIMARY KEY (coin_code)
);

CREATE TABLE IF NOT EXISTS public."Portfolio"
(
    login text NOT NULL,
    current_volume_usd double precision NOT NULL,
    current_volume_btc double precision,
    CONSTRAINT "Portfolio_pkey" PRIMARY KEY (login)
);

CREATE TABLE IF NOT EXISTS public."Exchanges"
(
    name text NOT NULL,
    score double precision NOT NULL,
    volume24h double precision NOT NULL,
    markets double precision NOT NULL,
    "Coins" double precision NOT NULL,
    last_volume double precision[] NOT NULL,
    CONSTRAINT "Exchanges_pkey" PRIMARY KEY (name)
);

ALTER TABLE IF EXISTS public."Deal"
    ADD FOREIGN KEY (login)
    REFERENCES public."Portfolio" (login) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Coin"
    ADD FOREIGN KEY (login)
    REFERENCES public."Portfolio" (login) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;